name: "Deliver package"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[release agent]')"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_CD }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test and verify coverage
        run: mvn clean test verify
      - name: Push coverage report to codecov
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Setup git
        run: git config user.email "frequentlymisseddeadlines+ciagent@gmail.com" && git config user.name "ci-agent"
      - name: Publish package
        run: mvn release:clean release:prepare release:perform
        env:
          GITHUB_ACTOR: FrequentlyMissedDeadlines
          GITHUB_TOKEN: ${{ secrets.PAT_CD }}
      - name: Set env
        run: echo "RELEASE_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.RELEASE_VERSION }}
          prerelease: false
          title: Release ${{ env.RELEASE_VERSION }}
          files: |
            target/*.jar
